#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AMD
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="AMDdb")]
	public partial class AMDDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertUser(User instance);
    partial void UpdateUser(User instance);
    partial void DeleteUser(User instance);
    partial void InsertItem(Item instance);
    partial void UpdateItem(Item instance);
    partial void DeleteItem(Item instance);
    #endregion
		
		public AMDDataContext() : 
				base(global::AMD.Properties.Settings.Default.AMDdbConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public AMDDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public AMDDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public AMDDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public AMDDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<User> Users
		{
			get
			{
				return this.GetTable<User>();
			}
		}
		
		public System.Data.Linq.Table<Item> Items
		{
			get
			{
				return this.GetTable<Item>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Users")]
	public partial class User : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _FullName;
		
		private string _Username;
		
		private string _Password;
		
		private string _Role;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnFullNameChanging(string value);
    partial void OnFullNameChanged();
    partial void OnUsernameChanging(string value);
    partial void OnUsernameChanged();
    partial void OnPasswordChanging(string value);
    partial void OnPasswordChanged();
    partial void OnRoleChanging(string value);
    partial void OnRoleChanged();
    #endregion
		
		public User()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FullName", DbType="NVarChar(50)")]
		public string FullName
		{
			get
			{
				return this._FullName;
			}
			set
			{
				if ((this._FullName != value))
				{
					this.OnFullNameChanging(value);
					this.SendPropertyChanging();
					this._FullName = value;
					this.SendPropertyChanged("FullName");
					this.OnFullNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Username", DbType="NVarChar(50)")]
		public string Username
		{
			get
			{
				return this._Username;
			}
			set
			{
				if ((this._Username != value))
				{
					this.OnUsernameChanging(value);
					this.SendPropertyChanging();
					this._Username = value;
					this.SendPropertyChanged("Username");
					this.OnUsernameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Password", DbType="NVarChar(50)")]
		public string Password
		{
			get
			{
				return this._Password;
			}
			set
			{
				if ((this._Password != value))
				{
					this.OnPasswordChanging(value);
					this.SendPropertyChanging();
					this._Password = value;
					this.SendPropertyChanged("Password");
					this.OnPasswordChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Role", DbType="NVarChar(50)")]
		public string Role
		{
			get
			{
				return this._Role;
			}
			set
			{
				if ((this._Role != value))
				{
					this.OnRoleChanging(value);
					this.SendPropertyChanging();
					this._Role = value;
					this.SendPropertyChanged("Role");
					this.OnRoleChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Items")]
	public partial class Item : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _ItemName;
		
		private System.Nullable<System.DateTime> _DateArrived;
		
		private System.Nullable<int> _BaleQuantity;
		
		private System.Nullable<double> _BaleActualPrice;
		
		private System.Nullable<double> _BaleShopPrice;
		
		private System.Nullable<int> _PiecesPerBale;
		
		private System.Nullable<double> _PiecesActualPrice;
		
		private System.Nullable<double> _PiecesShopPrice;
		
		private string _ItemComment;
		
		private System.Nullable<int> _TotalPieces;
		
		private System.Nullable<double> _BaleActualPriceTotal;
		
		private System.Nullable<double> _BaleShopPriceTotal;
		
		private System.Nullable<double> _PiecesPerBaleTotal;
		
		private System.Nullable<double> _PiecesActualPriceTotal;
		
		private System.Nullable<double> _PiecesShopPriceTotal;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnItemNameChanging(string value);
    partial void OnItemNameChanged();
    partial void OnDateArrivedChanging(System.Nullable<System.DateTime> value);
    partial void OnDateArrivedChanged();
    partial void OnBaleQuantityChanging(System.Nullable<int> value);
    partial void OnBaleQuantityChanged();
    partial void OnBaleActualPriceChanging(System.Nullable<double> value);
    partial void OnBaleActualPriceChanged();
    partial void OnBaleShopPriceChanging(System.Nullable<double> value);
    partial void OnBaleShopPriceChanged();
    partial void OnPiecesPerBaleChanging(System.Nullable<int> value);
    partial void OnPiecesPerBaleChanged();
    partial void OnPiecesActualPriceChanging(System.Nullable<double> value);
    partial void OnPiecesActualPriceChanged();
    partial void OnPiecesShopPriceChanging(System.Nullable<double> value);
    partial void OnPiecesShopPriceChanged();
    partial void OnItemCommentChanging(string value);
    partial void OnItemCommentChanged();
    partial void OnTotalPiecesChanging(System.Nullable<int> value);
    partial void OnTotalPiecesChanged();
    partial void OnBaleActualPriceTotalChanging(System.Nullable<double> value);
    partial void OnBaleActualPriceTotalChanged();
    partial void OnBaleShopPriceTotalChanging(System.Nullable<double> value);
    partial void OnBaleShopPriceTotalChanged();
    partial void OnPiecesPerBaleTotalChanging(System.Nullable<double> value);
    partial void OnPiecesPerBaleTotalChanged();
    partial void OnPiecesActualPriceTotalChanging(System.Nullable<double> value);
    partial void OnPiecesActualPriceTotalChanged();
    partial void OnPiecesShopPriceTotalChanging(System.Nullable<double> value);
    partial void OnPiecesShopPriceTotalChanged();
    #endregion
		
		public Item()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ItemName", DbType="NVarChar(50)")]
		public string ItemName
		{
			get
			{
				return this._ItemName;
			}
			set
			{
				if ((this._ItemName != value))
				{
					this.OnItemNameChanging(value);
					this.SendPropertyChanging();
					this._ItemName = value;
					this.SendPropertyChanged("ItemName");
					this.OnItemNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DateArrived", DbType="DateTime")]
		public System.Nullable<System.DateTime> DateArrived
		{
			get
			{
				return this._DateArrived;
			}
			set
			{
				if ((this._DateArrived != value))
				{
					this.OnDateArrivedChanging(value);
					this.SendPropertyChanging();
					this._DateArrived = value;
					this.SendPropertyChanged("DateArrived");
					this.OnDateArrivedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BaleQuantity", DbType="Int")]
		public System.Nullable<int> BaleQuantity
		{
			get
			{
				return this._BaleQuantity;
			}
			set
			{
				if ((this._BaleQuantity != value))
				{
					this.OnBaleQuantityChanging(value);
					this.SendPropertyChanging();
					this._BaleQuantity = value;
					this.SendPropertyChanged("BaleQuantity");
					this.OnBaleQuantityChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BaleActualPrice", DbType="Float")]
		public System.Nullable<double> BaleActualPrice
		{
			get
			{
				return this._BaleActualPrice;
			}
			set
			{
				if ((this._BaleActualPrice != value))
				{
					this.OnBaleActualPriceChanging(value);
					this.SendPropertyChanging();
					this._BaleActualPrice = value;
					this.SendPropertyChanged("BaleActualPrice");
					this.OnBaleActualPriceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BaleShopPrice", DbType="Float")]
		public System.Nullable<double> BaleShopPrice
		{
			get
			{
				return this._BaleShopPrice;
			}
			set
			{
				if ((this._BaleShopPrice != value))
				{
					this.OnBaleShopPriceChanging(value);
					this.SendPropertyChanging();
					this._BaleShopPrice = value;
					this.SendPropertyChanged("BaleShopPrice");
					this.OnBaleShopPriceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PiecesPerBale", DbType="Int")]
		public System.Nullable<int> PiecesPerBale
		{
			get
			{
				return this._PiecesPerBale;
			}
			set
			{
				if ((this._PiecesPerBale != value))
				{
					this.OnPiecesPerBaleChanging(value);
					this.SendPropertyChanging();
					this._PiecesPerBale = value;
					this.SendPropertyChanged("PiecesPerBale");
					this.OnPiecesPerBaleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PiecesActualPrice", DbType="Float")]
		public System.Nullable<double> PiecesActualPrice
		{
			get
			{
				return this._PiecesActualPrice;
			}
			set
			{
				if ((this._PiecesActualPrice != value))
				{
					this.OnPiecesActualPriceChanging(value);
					this.SendPropertyChanging();
					this._PiecesActualPrice = value;
					this.SendPropertyChanged("PiecesActualPrice");
					this.OnPiecesActualPriceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PiecesShopPrice", DbType="Float")]
		public System.Nullable<double> PiecesShopPrice
		{
			get
			{
				return this._PiecesShopPrice;
			}
			set
			{
				if ((this._PiecesShopPrice != value))
				{
					this.OnPiecesShopPriceChanging(value);
					this.SendPropertyChanging();
					this._PiecesShopPrice = value;
					this.SendPropertyChanged("PiecesShopPrice");
					this.OnPiecesShopPriceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ItemComment", DbType="NVarChar(100)")]
		public string ItemComment
		{
			get
			{
				return this._ItemComment;
			}
			set
			{
				if ((this._ItemComment != value))
				{
					this.OnItemCommentChanging(value);
					this.SendPropertyChanging();
					this._ItemComment = value;
					this.SendPropertyChanged("ItemComment");
					this.OnItemCommentChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TotalPieces", DbType="Int")]
		public System.Nullable<int> TotalPieces
		{
			get
			{
				return this._TotalPieces;
			}
			set
			{
				if ((this._TotalPieces != value))
				{
					this.OnTotalPiecesChanging(value);
					this.SendPropertyChanging();
					this._TotalPieces = value;
					this.SendPropertyChanged("TotalPieces");
					this.OnTotalPiecesChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BaleActualPriceTotal", DbType="Float")]
		public System.Nullable<double> BaleActualPriceTotal
		{
			get
			{
				return this._BaleActualPriceTotal;
			}
			set
			{
				if ((this._BaleActualPriceTotal != value))
				{
					this.OnBaleActualPriceTotalChanging(value);
					this.SendPropertyChanging();
					this._BaleActualPriceTotal = value;
					this.SendPropertyChanged("BaleActualPriceTotal");
					this.OnBaleActualPriceTotalChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BaleShopPriceTotal", DbType="Float")]
		public System.Nullable<double> BaleShopPriceTotal
		{
			get
			{
				return this._BaleShopPriceTotal;
			}
			set
			{
				if ((this._BaleShopPriceTotal != value))
				{
					this.OnBaleShopPriceTotalChanging(value);
					this.SendPropertyChanging();
					this._BaleShopPriceTotal = value;
					this.SendPropertyChanged("BaleShopPriceTotal");
					this.OnBaleShopPriceTotalChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PiecesPerBaleTotal", DbType="Float")]
		public System.Nullable<double> PiecesPerBaleTotal
		{
			get
			{
				return this._PiecesPerBaleTotal;
			}
			set
			{
				if ((this._PiecesPerBaleTotal != value))
				{
					this.OnPiecesPerBaleTotalChanging(value);
					this.SendPropertyChanging();
					this._PiecesPerBaleTotal = value;
					this.SendPropertyChanged("PiecesPerBaleTotal");
					this.OnPiecesPerBaleTotalChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PiecesActualPriceTotal", DbType="Float")]
		public System.Nullable<double> PiecesActualPriceTotal
		{
			get
			{
				return this._PiecesActualPriceTotal;
			}
			set
			{
				if ((this._PiecesActualPriceTotal != value))
				{
					this.OnPiecesActualPriceTotalChanging(value);
					this.SendPropertyChanging();
					this._PiecesActualPriceTotal = value;
					this.SendPropertyChanged("PiecesActualPriceTotal");
					this.OnPiecesActualPriceTotalChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PiecesShopPriceTotal", DbType="Float")]
		public System.Nullable<double> PiecesShopPriceTotal
		{
			get
			{
				return this._PiecesShopPriceTotal;
			}
			set
			{
				if ((this._PiecesShopPriceTotal != value))
				{
					this.OnPiecesShopPriceTotalChanging(value);
					this.SendPropertyChanging();
					this._PiecesShopPriceTotal = value;
					this.SendPropertyChanged("PiecesShopPriceTotal");
					this.OnPiecesShopPriceTotalChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
